/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Sara
 */
public class VentanaVisor extends javax.swing.JFrame {

    public int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * Creates new form VentanaVisor
     */
    public VentanaVisor() {
        setResizable(false);
        setTitle("Visor de imágenes");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnContinuar = new javax.swing.JButton();
        btnSalirVisor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LabelImagen = new javax.swing.JLabel();
        btnDetener = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 202, 30));

        btnContinuar.setBackground(new java.awt.Color(0, 0, 28));
        btnContinuar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("CONTINUAR");
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 190, 30));

        btnSalirVisor.setBackground(new java.awt.Color(0, 0, 28));
        btnSalirVisor.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnSalirVisor.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirVisor.setText("SALIR");
        jPanel1.add(btnSalirVisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 170, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 530, 430));

        btnDetener.setBackground(new java.awt.Color(0, 0, 28));
        btnDetener.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnDetener.setForeground(new java.awt.Color(255, 255, 255));
        btnDetener.setText("DETENER");
        jPanel1.add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/estrellas (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 550, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImagen;
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnDetener;
    public javax.swing.JButton btnSalirVisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables


    public void mostrarImagen(File imagen) {
        ImageIcon icono = new ImageIcon(imagen.getPath());
        Image imagenEscalada = icono.getImage().getScaledInstance(530, 430, Image.SCALE_SMOOTH);
        LabelImagen.setIcon(new ImageIcon(imagenEscalada));
        repaint();
    }
    public void aviso(String x){
        System.out.println(x);
    }

    public void cerrar(){
        dispose();
    }
    
}
